### PR TITLE
Fix BrowerURLParser

### LINKED ISSUE #416: [DApp] Browser enter query functionality
If you enter "radar relay" in the browser it will forward you to the google, expected.
But if you enter only one-word "radar" it will give you an error.

We need to have a better for handling query input.

Look into `BrowserURLParser`, make sure to cover it with tests

Example:
"radar relay" => goes to google query
"radar" => goes to Google (not working)
"test.com" => goes to test.com
"https://test.com" => goes to test.com

### PR DESCRIPTION
**Pull request by aleph7**
fix #416

### CODE REVIEW

File: TrustTests/Browser/Types/BrowserURLParserTests.swift [hunk 1]
```diff
@@ -52,7 +52,15 @@ class BrowserURLParserTests: XCTestCase {
...
-        XCTAssertEqual(result?.absoluteString, "https://" + string)
+        XCTAssertEqual(result?.absoluteString, "https://\(string)")
+    }
+
+    func testParseLongDomain() {
+        let parser = BrowserURLParser()
+        let string = "test.trustwalletapp.info"
+        let result = parser.url(from: string)
+
+        XCTAssertEqual(result?.absoluteString, "https://\(string)")
```
Comment (vikmeup) [inline TrustTests/Browser/Types/BrowserURLParserTests.swift]: does it have to redirect to https always?
