### PR TITLE
Fix of the data source.

### LINKED ISSUE #432: Wallets views - offset
If you have two sections in the table view, you say 0 rows for the first section, it add extra spacing, this should be fixed

Current:
simulator screen shot - iphone x - 2018-03-07 at 13 35 15

### PR DESCRIPTION
**Pull request by OlegGordiichuk**
I update data source to respect section count. 

Fix #432

### CODE REVIEW

File: Trust/Accounts/ViewModels/AccountsViewModel.swift [hunk 1]
```diff
@@ -5,70 +5,58 @@ import TrustKeystore
...
-        switch section {
-        case Sections.hdWallets:
-            return hdWallets.isEmpty ? .none : NSLocalizedString("wallet.section.hdWallet.title", value: "HD Wallet", comment: "")
-        case Sections.regularWallets:
-            return .none
-        default: return .none
+        guard walletsTypes.count == 2 && section == 0 else {
+            return nil
         }
+        return NSLocalizedString("wallet.section.hdWallet.title", value: "HD Wallet", comment: "")
```
Comment (vikmeup) [inline Trust/Accounts/ViewModels/AccountsViewModel.swift]: I think we want to show `HD wallet` if `walletsTypes.count == 1` a well

Comment (OlegGordiichuk) [reply Trust/Accounts/ViewModels/AccountsViewModel.swift]: Hmm yeah it is true we should have some another way for it
