### PR TITLE
Fix for QR code scanner.

### LINKED ISSUE #245: SendViewController.swift line 223
#### in specialized SendViewController.reader(QRCodeReaderViewController!, didScanResult : String!) -> ()

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/trust3/ios/apps/com.sixdays.trust/issues/5a6820798cb3c2fa6379ca2a?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/trust3/ios/apps/com.sixdays.trust/issues/5a6820798cb3c2fa6379ca2a?utm_medium=service_hooks-github&utm_source=issue_impact)

### PR DESCRIPTION
**Pull request by OlegGordiichuk**
Fix #245

### CODE REVIEW

File: Trust/Transfer/ViewControllers/SendViewController.swift [hunk 1]
```diff
@@ -278,12 +278,16 @@ class SendViewController: FormViewController {
 }
 
 extension SendViewController: QRCodeReaderDelegate {
+     //We should stop scannin when recive result from QR code reader.
```
Comment (michaelScoff) [inline Trust/Transfer/ViewControllers/SendViewController.swift]: can you remove this comment?

Comment (OlegGordiichuk) [reply Trust/Transfer/ViewControllers/SendViewController.swift]: done
