### PR TITLE
Feature/collectibles ui fixes

### LINKED ISSUE #584: Split collectibles into categories
I'm getting more collectibles now, it's hard to manage them, it would be great to split those into categories, rather than one list.

### PR DESCRIPTION
**Pull request by OlegGordiichuk**
- Update ui of the elements
- Made colors to be more softer 
- Add small animations 
- Clean code 
Fix #584

### CODE REVIEW

File: Trust/Tokens/ViewModels/NonFungibleTokenViewModel.swift [hunk 1]
```diff
@@ -18,11 +18,15 @@ class NonFungibleTokenViewModel {
     }
 
     var headerTitleTextColor: UIColor {
-        return UIColor(hex: "555357")
+        return UIColor(hex: "333333")
```
Comment (MillerApps) [inline Trust/Tokens/ViewModels/NonFungibleTokenViewModel.swift]: Can you add this to `AppStyle`?

File: Trust/Tokens/ViewModels/NonFungibleTokenViewModel.swift [hunk 2]
```diff
@@ -18,11 +18,15 @@ class NonFungibleTokenViewModel {
...
+    }
+
+    var tableViewBacgroundColor: UIColor {
+        return UIColor.white
     }
 
     var headerTitleFont: UIFont {
-        return UIFont.systemFont(ofSize: 14, weight: UIFont.Weight.medium)
+        return UIFont.systemFont(ofSize: 21, weight: UIFont.Weight.regular)
```
Comment (MillerApps) [inline Trust/Tokens/ViewModels/NonFungibleTokenViewModel.swift]: Same here.

File: Trust/Tokens/Views/NonFungibleTokenViewCell.swift [hunk 3]
```diff
@@ -13,22 +14,25 @@ class NonFungibleTokenViewCell: UITableViewCell {
         super.awakeFromNib()
         collectionView.dataSource = self
         collectionView.delegate = self
-        collectionView.register(R.nib.nonFungibleCollectionViewCell(), forCellWithReuseIdentifier: R.nib.nonFungibleCollectionViewCell.name)
+     collectionView.register(R.nib.nonFungibleCollectionViewCell(), forCellWithReuseIdentifier: R.nib.nonFungibleCollectionViewCell.name)
```
Comment (MillerApps) [inline Trust/Tokens/Views/NonFungibleTokenViewCell.swift]: Spacing is a bit off.

File: Trust/Tokens/ViewControllers/NFTokenViewController.swift [hunk 4]
```diff
@@ -37,6 +38,17 @@ class NFTokenViewController: UIViewController {
 
     let token: NonFungibleTokenObject
 
+    lazy var imageView: UIImageView = {
+        let imageView = UIImageView()
+        imageView.translatesAutoresizingMaskIntoConstraints = false
+        imageView.kf.setImage(
+            with: viewModel.imageURL,
+            placeholder: .none
```
Comment (vikmeup) [inline Trust/Tokens/ViewControllers/NFTokenViewController.swift]: placeholder is missing

File: Trust/Tokens/ViewControllers/NonFungibleTokensViewController.swift [hunk 5]
```diff
@@ -96,7 +96,7 @@ extension NonFungibleTokensViewController: StatefulViewController {
 
 extension NonFungibleTokensViewController: UITableViewDelegate {
     func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
-        return 260
+        return 256
```
Comment (vikmeup) [inline Trust/Tokens/ViewControllers/NonFungibleTokensViewController.swift]: can we make 250? and make it few pixels smaller in width

File: Trust/Tokens/Views/NonFungibleTokenViewCell.swift [hunk 6]
```diff
@@ -13,22 +14,25 @@ class NonFungibleTokenViewCell: UITableViewCell {
...
     func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
-        guard let model = viewModel else {
+        guard let model = viewModel, let cell = collectionView.cellForItem(at: indexPath) as? NonFungibleCollectionViewCell else {
             return
         }
-
-        let tokenDictionary: [String: NonFungibleTokenObject] = ["token": model.token(for: indexPath)]
+        let token = model.token(for: indexPath)
+        let heroId = token.uniqueID
+        cell.hero.id = heroId
```
Comment (vikmeup) [inline Trust/Tokens/Views/NonFungibleTokenViewCell.swift]: is there a way to avoid Hero? just trying to reduce number of libs

File: Trust/Tokens/ViewModels/NonFungibleTokenViewModel.swift (hunk 1 above)
Comment (OlegGordiichuk) [reply Trust/Tokens/ViewModels/NonFungibleTokenViewModel.swift]: Done

File: Trust/Tokens/ViewModels/NonFungibleTokenViewModel.swift (hunk 2 above)
Comment (OlegGordiichuk) [reply Trust/Tokens/ViewModels/NonFungibleTokenViewModel.swift]: Done

File: Trust/Tokens/Views/NonFungibleTokenViewCell.swift (hunk 3 above)
Comment (OlegGordiichuk) [reply Trust/Tokens/Views/NonFungibleTokenViewCell.swift]: Done

File: Trust/Tokens/ViewControllers/NFTokenViewController.swift (hunk 4 above)
Comment (OlegGordiichuk) [reply Trust/Tokens/ViewControllers/NFTokenViewController.swift]: Done

File: Trust/Tokens/ViewControllers/NonFungibleTokensViewController.swift (hunk 5 above)
Comment (OlegGordiichuk) [reply Trust/Tokens/ViewControllers/NonFungibleTokensViewController.swift]: Done

File: Trust/Tokens/Views/NonFungibleTokenViewCell.swift (hunk 6 above)
Comment (OlegGordiichuk) [reply Trust/Tokens/Views/NonFungibleTokenViewCell.swift]: Hmm I will add small issue to use own animation delegate. https://github.com/TrustWallet/trust-wallet-ios/issues/711
