### PR TITLE
Attempt to fix issue #485

### LINKED ISSUE #485: Import wallet QR Code Reader not working
The QR Code reader doest work on the import screen. 

To reproduce: Try to import a private key from a QR code.

Note: in my test the stock camera app could successfully read the code.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

### PR DESCRIPTION
**Pull request by MillerApps**
An attempt to fix #485

### CODE REVIEW

File: Trust/Wallet/ViewControllers/ImportWalletViewController.swift [hunk 1]
```diff
@@ -253,6 +253,7 @@ class ImportWalletViewController: FormViewController {
 
     func setValueForCurrentField(string: String) {
         let type = ImportSelectionType(title: segmentRow?.value)
+        guard let result = QRURLParser.from(string: string) else { return }
```
Comment (vikmeup) [inline Trust/Wallet/ViewControllers/ImportWalletViewController.swift]: can you call this function in .address case? 

Nice catch
